const EmailTypes = {
    EMAIL_CREATE: "EMAIL_CREATE",
    EMAIL_CREATE_SUCCESS: "EMAIL_CREATE_SUCCESS",
    GET_ALL_EMAIL: "GET_ALL_EMAIL",
    GET_ALL_EMAIL_SUCCESS: "GET_ALL_EMAIL_SUCCESS",
    EMAIL_UPDATE: "EMAIL_UPDATE",
    EMAIL_UPDATE_SUCCESS: "EMAIL_UPDATE_SUCCESS",
    EMAIL_DELETE: "EMAIL_DELETE",
    EMAIL_DELETE_SUCCESS: "EMAIL_DELETE_SUCCESS",
  };
  
  export default EmailTypes;
  