const EmailTypes = {
    EMAIL_CREATE: "EMAIL_CREATE",
    CREATE_SUCCESS: "CREATE_SUCCESS",
    GET_ALL_EMAIL: "GET_ALL_EMAIL",
    GET_ALL_EMAIL_SUCCESS: "GET_ALL_EMAIL_SUCCESS",
    UPDATE_EMAIL: "UPDATE_EMAIL",
    UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
    DELETE_EMAIL: "DELETE_EMAIL",
    DELETE_EMAIL_SUCCESS: "DELETE_EMAIL_SUCCESS",
  };
  
  export default EmailTypes;
  