const resourceTypes = {
  IMAGE_FETCH: "IMAGE_FETCH",
  IMAGE_FETCH_SUCCESS: "IMAGE_FETCH_SUCCESS",
  IMAGE_UPLOAD: "IMAGE_UPLOAD",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  IMAGE_UPLOAD_FAIL: "IMAGE_UPLOAD_FAIL",
  IMAGE_DELETE: "IMAGE_DELETE",
};

export default resourceTypes;